### ISSUE TITLE
code in npm and github is different

### ISSUE THREAD

**Issue by JSProto** [astur/tress#1]
npm code with an error
`
var _status = (job) => {
        _queue.waiting.indexOf(job) >= 0 ? 'waiting' :
        _queue.running.indexOf(job) >= 0 ? 'active' :
        _queue.finished.indexOf(job) >= 0 ? 'finished' :
        _queue.failed.indexOf(job) >= 0 ? 'failed' :
        'missing'
    };
`

'_queue.running.indexOf' must be '_queue.active.indexOf'.

**Comment by astur** [comment]
Fixed by publishing v1.0.4 on npm. Thank you.
